version: "3.9"

services:
    db:
        image:  postgres:latest
        hostname: postgres_db
        environment:
            POSTGRES_PASSWORD: admin
        expose: 
            - 5432
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
                
            
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - "db"

        ports: 
            - "8080:8080"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3

