name: dp

services:
  db:
    image: postgres:latest
    hostname: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    # for local debug purposes
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  app:
    hostname: dp-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    # for local debug purposes
    ports:
      - "8080:80"
    expose:
      - 80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    env_file:
      - path: ./.env
    networks:
      - api
      - internal

  minio-storage:
    image: quay.io/minio/minio
    ports:
      # for local debug purposes
      - 9000:9000
      - 9001:9001
    expose:
      - 9000:9000
      - 9001:9001
    hostname: dp-object-storage
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    networks:
      - internal

volumes:
  postgres-data:
  minio-data:

networks:
  internal:
  api:
    name: dp-api

